import json
import os
import re
from urllib.request import urlopen, Request

# Constants
DATA_URL = "https://github.com/EhTagTranslation/Database/releases/latest/download/db.text.json"
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

def fetch_data(url: str) -> dict:
    print(f"Downloading data from {url}...")
    req = Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urlopen(req) as response:
            return json.load(response)
    except Exception as e:
        print(f"Error fetching data: {e}")
        return {}

def process_tags(source_data: dict) -> dict:
    if not source_data or "data" not in source_data:
        return {}

    output = {
        "tag": {},
        "parody": {},
        "character": {},
        "group": {},
        "artist": {}
    }

    merge_to_tag = {"female", "male", "mixed", "location", "other"}
    emoji_pattern = re.compile(r'[\U00010000-\U0010ffff]')

    for item in source_data["data"]:
        namespace = item.get("namespace")
        tags_map = item.get("data", {})
        target_dict = None

        if namespace in merge_to_tag:
            target_dict = output["tag"]
        elif namespace in output:
            target_dict = output[namespace]
        
        if target_dict is not None:
            for key, value in tags_map.items():
                if "name" in value:
                    raw_name = value["name"]
                    clean_name = emoji_pattern.sub('', raw_name).strip()
                    if clean_name:
                        target_dict[key.lower()] = clean_name

    return output

def escape_rust_string(s: str) -> str:
    """Escape a string for use in Rust source code."""
    return s.replace('\\', '\\\\').replace('"', '\\"')

def generate_phf_map(name: str, data: dict, indent: str = "") -> str:
    """Generate a phf_map! macro invocation."""
    if not data:
        return f"{indent}pub static {name}: phf::Map<&'static str, &'static str> = phf::phf_map! {{}};\n"
    
    lines = [f"{indent}pub static {name}: phf::Map<&'static str, &'static str> = phf::phf_map! {{"]
    for key, value in sorted(data.items()):
        escaped_key = escape_rust_string(key)
        escaped_value = escape_rust_string(value)
        lines.append(f'{indent}    "{escaped_key}" => "{escaped_value}",')
    lines.append(f"{indent}}};")
    return "\n".join(lines)

def generate_rust_file(data: dict) -> str:
    """Generate the complete Rust source file."""
    lines = [
        "// This file is auto-generated by fetch_localization_cn.py",
        "// Do not edit manually!",
        "",
        "#![allow(clippy::unreadable_literal)]",
        "",
    ]
    
    # Generate forward maps
    lines.append(generate_phf_map("CN_TAG", data.get("tag", {})))
    lines.append("")
    lines.append(generate_phf_map("CN_PARODY", data.get("parody", {})))
    lines.append("")
    lines.append(generate_phf_map("CN_CHARACTER", data.get("character", {})))
    lines.append("")
    lines.append(generate_phf_map("CN_GROUP", data.get("group", {})))
    lines.append("")
    lines.append(generate_phf_map("CN_ARTIST", data.get("artist", {})))
    lines.append("")
    
    # Generate reverse map for tags (Chinese -> English)
    reverse_tag = {v.lower(): k for k, v in data.get("tag", {}).items()}
    lines.append(generate_phf_map("CN_TAG_REVERSE", reverse_tag))
    
    return "\n".join(lines)

def save_rust_file(content: str, filename: str):
    base_dir = os.path.dirname(os.path.realpath(__file__))
    src_dir = os.path.join(base_dir, "..", "src")
    
    file_path = os.path.join(src_dir, filename)
    
    print(f"Saving to {file_path}...")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Done. Generated {len(content)} bytes.")

def cleanup_old_json():
    """Remove the old JSON file if it exists."""
    base_dir = os.path.dirname(os.path.realpath(__file__))
    json_path = os.path.join(base_dir, "..", "res", "localization_cn.json")
    
    if os.path.exists(json_path):
        print(f"Removing old JSON file: {json_path}")
        os.remove(json_path)

if __name__ == "__main__":
    raw_data = fetch_data(DATA_URL)
    if raw_data:
        processed_data = process_tags(raw_data)
        
        # Print stats
        for key, val in processed_data.items():
            print(f"  {key}: {len(val)} entries")
        
        rust_code = generate_rust_file(processed_data)
        save_rust_file(rust_code, "localization_cn.rs")
        
        # Clean up old JSON file
        cleanup_old_json()